
name: Ubuntu 24.04, R 4.6
on:
  workflow_dispatch:
  schedule:
    - cron:  '43 16 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    container: ghcr.io/r-hub/containers/ubuntu-gcc15:latest
    steps:
    - name: Check Distro and R version
      run: |
        #
        readRenviron("/etc/os-release")
        if (Sys.getenv("ID") != "ubuntu") stop("Not Ubuntu")
        if (Sys.getenv("VERSION_ID") != "24.04") stop("Not Ubuntu 24.04")
        if (getRversion() < "4.6.0" || getRversion() >= "4.7.0") {
          stop("Not R 4.6.x")
        }
      shell: Rscript {0}
    - uses: actions/checkout@v3
    - uses: r-hub/repos/actions/update-repo@main
      with:
        directory: ubuntu-24.04/4.6
        token: ${{ secrets.CRANATGH_GITHUB_TOKEN }}
